### PR TITLE
Updated README file 

### PR DESCRIPTION
**Pull request by Ankit-11525**

### CODE REVIEW

**Comment by Ankit-11525** [comment]
Take a review to my readme and please merge it in your main README

**Comment by Ankit-11525** [comment]
PR for issue #7

**Comment by akhil-aggarwal** [comment]
It contains 2 conflicts according to Github. Please correct them. I think you are facing due to your <<<<<main command. Please check

**Comment by akhil-aggarwal** [comment]
Rest all looks good. Please resolve the conflicts. I will merge it.

**Comment by Ankit-11525** [comment]
@akhil-aggarwal Now it is resolved !!
PR for issue #7

**Pull request merged**
